backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Main Image", name: "mainImage", widget: "image"}
      - {label: "Alt Image 1", name: "altImage1", widget: "image"}
      - {label: "Alt Image 2", name: "altImage2", widget: "image"}
      - {label: "Details", name: "details", widget: "list", fields: [{label: "Detail", name: "detail", widget: "string"}]} 